### PR TITLE
Fixes Links on Blocks using JSON:API 

### LINKED ISSUE #1080: JSON:API -- Blocks with Links need those links to be relative to base url
JSON API returns relative paths for Articles, People, etc. Need to make the returned and rendered "Read More" or similar links relative to the base URL, instead of just using what's provided similar to how we did the API requests. 

Likely affects:
- Article List page
- People List page
- Article List, Article Feature, Article Slider, Article Grid blocks
- People List block

Possibly affects:
- Issue blocks
- Category and Tag cloud blocks
- Collection items
... might want to check any API blocks/pages

https://www.colorado.edu/demos/documentation/articles-and-issues/article-list-page
https://www.colorado.edu/demos/documentation/people/people-list-pages/people-list-page-list-display

### PR DESCRIPTION
**Pull request by patrickbrown-io**
Previously, Pages and Blocks rendering content via JSON:API would use relative pathing, which resulted in content on multi-sites to 404.

This has been corrected on the following:
### Pages
- People List Page
- Article List page
- Issue Archive

### Blocks
- People List Block

- Current Issue Block
- Latest Issue Block

- Article List Block
- Article Feature
- Article Grid
- Article Slider

- Category Cloud
- Tag Cloud

- Collection Block

Resolves #1080

### CODE REVIEW

File: js/ucb-article-list.js [hunk 1]
```diff
@@ -90,6 +90,7 @@
         fetch(JSONURL)
           .then((reponse) => reponse.json())
           .then((data) => {
+            console.log('am i here', baseURI)
```
Comment (jcsparks) [inline js/ucb-article-list.js:93]: Looks like we have a stray debug message in here.

**Review by jcsparks — APPROVED** [review]
